# Generated by Django 5.2.4 on 2025-07-18 02:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField()),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('valorGasto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
            ],
        ),
    ]
