# Generated by Django 5.2.4 on 2025-09-23 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('bank', models.CharField(max_length=50)),
                ('type_card', models.IntegerField(choices=[(1, 'Credito'), (2, 'Debito'), (3, 'Credito/Debito')], default=1)),
                ('limit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('color', models.CharField(blank=True, default='#000000', max_length=7, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='user.usermodel')),
            ],
        ),
    ]
