# Generated by Django 5.2.4 on 2025-09-30 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardmodel',
            old_name='brand',
            new_name='bander',
        ),
    ]
