# Generated by Django 5.2.4 on 2025-09-23 13:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('type_transfer', models.IntegerField(choices=[(1, 'Lazer'), (2, 'Alimentação'), (3, 'Saude'), (4, 'Contas'), (5, 'Transporte'), (6, 'Outros')], default=6)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.IntegerField(choices=[(1, 'Credito'), (2, 'Débito'), (3, 'Dinheiro'), (4, 'Pix')], default=3)),
                ('card_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='card.cardmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='user.usermodel')),
            ],
        ),
    ]
